# MongoDB Database
MONGODB_URI=mongodb+srv://mitchleytapiwa2_db_user:D6Zr2jDQhUUmQh0L@cluster0.yp01ize.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
DATABASE_NAME=AfricanLeague


# Email Service (Gmail)
EMAIL_USER=tapiwadinner8@gmail.com
EMAIL_PASSWORD=jyuc frsj uxdf bjle
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587

# Admin credentials for the application
ADMIN_EMAIL = "admin@africanleague.com"
ADMIN_PASSWORD = "admin123"
