# PLACEHOLDER - Add real secrets in Streamlit Cloud
MONGODB_URI = "add_real_mongodb_uri_in_streamlit_cloud"
ADMIN_EMAIL = "admin@africanleague.com"
ADMIN_PASSWORD = "admin123"
OPENAI_API_KEY = "add_real_openai_key_in_streamlit_cloud_optional"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "add_real_email_in_streamlit_cloud"
SENDER_PASSWORD = "add_real_password_in_streamlit_cloud"
